settings:
  APP_DISPLAY_NAME: Element X
  PRODUCTION_APP_NAME: Element
  BASE_APP_GROUP_IDENTIFIER: com.plx
  BASE_BUNDLE_IDENTIFIER: com.plx.encipherX
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: 472BNX28V2
